import turtle
turtle.shape('turtle')

def draw(n):
    if n == 0: 
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.penup()
        turtle.forward(100)
        turtle.pendown()

    elif n == 1:
        turtle.penup()
        turtle.right(90)
        turtle.forward(50)
        turtle.left(135)
        turtle.pendown()
        turtle.forward(70)
        turtle.right(135)
        turtle.forward(100)
        turtle.penup()
        turtle.left(180)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(50)
        turtle.pendown()

    elif n == 2: 
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(45)
        turtle.forward(70)
        turtle.left(135)
        turtle.forward(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(50)
        turtle.pendown()
    
    elif n == 3: 
        turtle.forward(50)
        turtle.right(135)
        turtle.forward(70)
        turtle.left(135)
        turtle.forward(50)
        turtle.right(135)
        turtle.forward(70)
        turtle.penup()
        turtle.left(135)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.pendown()

    elif n == 4: 
        turtle.right(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(180)
        turtle.forward(100)
        turtle.penup()
        turtle.right(90)
        turtle.forward(50)
        turtle.pendown()

    elif n == 5: 
        turtle.forward(50)
        turtle.left(180)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.penup()
        turtle.left(180)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.pendown()

    elif n == 6: 
        turtle.penup()
        turtle.forward(50)
        turtle.pendown()
        turtle.right(135)
        turtle.forward(70)
        turtle.left(45)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.penup()
        turtle.right(180)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.pendown()

    elif n == 7:
        turtle.forward(50)
        turtle.right(135)
        turtle.forward(70)
        turtle.left(45)
        turtle.forward(50)
        turtle.penup()
        turtle.left(90)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)

    elif n == 8:
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(180)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.penup()
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.pendown()

    elif n == 9:
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(50)
        turtle.left(180)
        turtle.forward(50)
        turtle.left(90)
        turtle.forward(50)
        turtle.right(135)
        turtle.forward(70)
        turtle.penup()
        turtle.left(135)
        turtle.forward(100)
        turtle.left(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.pendown()        

L = list(map(int, input().split()))


for i in range(len(L)):
    if L[i] == 1: draw(1)
    elif L[i] == 2: draw(2)
    elif L[i] == 3: draw(3)
    elif L[i] == 4: draw(4)
    elif L[i] == 5: draw(5)
    elif L[i] == 6: draw(6)
    elif L[i] == 7: draw(7)
    elif L[i] == 8: draw(8)
    elif L[i] == 9: draw(9)
    elif L[i] == 0: draw(0)

turtle.mainloop()
    
