
import turtle
turtle.shape('turtle')
turtle.goto(0,0)
turtle.color("yellow")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.goto(-50,96)
turtle.color("blue")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()
turtle.penup()
turtle.goto(30,96)
turtle.pendown()
turtle.color("green")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()
turtle.penup()
turtle.goto(-10,76)
turtle.pendown()
turtle.color("black")
turtle.width(10)
turtle.goto(-10,56)
turtle.penup()
turtle.goto(-40,36)
turtle.pendown()
turtle.color("red")
turtle.width(20)
turtle.right(40)
for i in range (90):
   turtle.forward(1)
   turtle.left(1)
